# Generated by Django 5.2.3 on 2025-07-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Pokemon', 'Pokémon'), ('OnePiece', 'One Piece'), ('MTG', 'Magic: The Gathering')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
