# Generated by Django 5.2.3 on 2025-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
