# Generated by Django 5.2.3 on 2025-10-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_card_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
