# Generated by Django 5.2.3 on 2025-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_card_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='set_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Set'),
        ),
    ]
