# Generated by Django 5.2.3 on 2025-07-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('card_name', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('nm', 'Near Mint'), ('lp', 'Lightly Played'), ('mp', 'Moderately Played'), ('hp', 'Heavily Played'), ('damaged', 'Damaged')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('image_front', models.ImageField(upload_to='card_submissions/')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='card_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
