# Generated by Django 5.2.3 on 2025-07-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
