# Generated by Django 5.2.3 on 2025-08-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=120)),
                ('front_image', models.ImageField(upload_to='grading/%Y/%m/%d/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='grading/%Y/%m/%d/')),
                ('score_centering', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('score_surface', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('score_edges', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('score_corners', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('score_color', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('predicted_grade', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('predicted_label', models.CharField(blank=True, max_length=20)),
                ('explanation_md', models.TextField(blank=True)),
                ('needs_better_photos', models.BooleanField(default=False)),
                ('photo_feedback', models.CharField(blank=True, max_length=300)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
