# Generated by Django 5.2.3 on 2025-08-14 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='graderequest',
            name='game',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='GradedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=255)),
                ('front_image', models.ImageField(upload_to='graded_cards/front/')),
                ('back_image', models.ImageField(upload_to='graded_cards/back/')),
                ('score_centering', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('score_surface', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('score_edges', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('score_corners', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('score_color', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('predicted_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('predicted_label', models.CharField(blank=True, max_length=100)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('needs_better_photos', models.BooleanField(default=False)),
                ('photo_feedback', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('human_verified_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
