# Generated by Django 5.2.3 on 2025-08-21 11:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shippingmethod_order_items_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method_code',
            field=models.SlugField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='orders.shippingmethod')),
            ],
            options={
                'unique_together': {('method', 'country')},
            },
        ),
    ]
