# Generated by Django 5.2.3 on 2025-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping_method_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='code',
            field=models.SlugField(default='Standard', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='sort_order',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='free_over',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
