# Generated by Django 5.2.3 on 2025-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_shippingmethod_options_shippingmethod_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_debited',
            field=models.BooleanField(default=False),
        ),
    ]
